theme: jekyll-theme-cayman
title: Large Animatable Human Model (LHM)
description: A framework for reconstructing 3D animatable humans from single images
baseurl: ""
url: "https://aigraphix.github.io"
github_username: aigraphix
include:
  - "*.md"
  - "CHANGELOG.md"
  - "LICENSE"
  - "README.md"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap 